enviroment:
  matrix:
    # node.js
    - nodejs_version: "9"

install:
  #get latest stable version of node
  - ps: Install-Product node $env:nodejs_version
  #install modules
  - npm install

test_script:
  #Output useful info for debugging
  - node --version
  - npm --version
  # run tests
  - npm test

#dont actually build
build: off
